# Generated by Django 5.0.6 on 2024-06-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='session_id',
        ),
        migrations.DeleteModel(
            name='SavedItem',
        ),
    ]
