# Generated by Django 5.0.6 on 2024-06-30 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0006_alter_cartitems_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='old_price',
            new_name='price',
        ),
    ]
